version: "3.8"
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: pnpm dev
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
