worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;
  keepalive_timeout 65;
  server_tokens off;
  client_max_body_size 10m;
  
  # Configure shared memory zone for caching
  # Cloud Run memory is limited (512Mi), so we cap the cache size at 100m.
  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=EDGE_CACHE:10m max_size=100m inactive=24h use_temp_path=off;

  include /etc/nginx/conf.d/*.conf;
}
